version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: redis:6.2-alpine
    restart: always
      #ports:
      #  - '6379:6379'
    command: redis-server --appendonly yes --appendfilename study.aof --loglevel warning 
    volumes: 
      - cache:/data
    networks:
      - app-tier

  ui:
    image: ui_img
    build:
      context: .
      dockerfile: Dockerfile.ui
    command: python3 -u ts4ea/uiB.py
    ports:
      - '7860:7860'
    networks:
    - app-tier
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"

  traefik:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/traefik/traefik.dev.toml:/etc/traefik/traefik.toml"

  server:
    image: server_img
    build:
      context: .
      dockerfile: Dockerfile.server
    command: python3 -u ts4ea/server.py
    networks:
    - app-tier

volumes:
  cache:
    driver: local

